import type { Trip, TripStop } from '../types';

export function printItinerary(trip: Trip, stops: TripStop[]) {
  const html = `
<!DOCTYPE html>
<html>
<head>
  <title>${trip.name} — TrailCamp Itinerary</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', system-ui, sans-serif; padding: 40px; color: #1a1a2e; line-height: 1.6; }
    h1 { font-size: 28px; margin-bottom: 4px; color: #ea580c; }
    .subtitle { color: #64748b; font-size: 14px; margin-bottom: 24px; }
    .stop { padding: 16px 0; border-bottom: 1px solid #e2e8f0; display: flex; gap: 16px; }
    .stop-num { width: 32px; height: 32px; background: #ea580c; color: white; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: 700; font-size: 14px; flex-shrink: 0; }
    .stop-info { flex: 1; }
    .stop-name { font-weight: 700; font-size: 16px; }
    .stop-meta { color: #64748b; font-size: 13px; margin-top: 2px; }
    .stop-coords { color: #94a3b8; font-size: 11px; font-family: monospace; }
    .stop-notes { color: #475569; font-size: 13px; margin-top: 4px; font-style: italic; }
    .footer { margin-top: 32px; color: #94a3b8; font-size: 11px; text-align: center; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>🏍️ ${trip.name}</h1>
  <div class="subtitle">${stops.length} stops · Generated by TrailCamp</div>
  ${stops.map((stop, i) => `
    <div class="stop">
      <div class="stop-num">${i + 1}</div>
      <div class="stop-info">
        <div class="stop-name">${stop.name || stop.location_name || 'Stop'}</div>
        <div class="stop-meta">
          ${stop.nights ? `${stop.nights} night${stop.nights > 1 ? 's' : ''}` : 'Day stop'}
          ${stop.arrival_date ? ` · ${stop.arrival_date}` : ''}
        </div>
        <div class="stop-coords">${stop.latitude.toFixed(5)}, ${stop.longitude.toFixed(5)}</div>
        ${stop.notes ? `<div class="stop-notes">${stop.notes}</div>` : ''}
      </div>
    </div>
  `).join('')}
  <div class="footer">TrailCamp — Dirt Bike Trails & Camping Map</div>
</body>
</html>`;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 500);
  }
}
